export const ARTIST_DATA: { name: string; primaryGenre: string }[] = [
  // R&B/Hip-Hop (40)
  { name: 'Drake', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Kendrick Lamar', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Travis Scott', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'J. Cole', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Nicki Minaj', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Cardi B', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Future', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Lil Baby', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Lil Durk', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Gunna', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Young Thug', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Roddy Ricch', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'DaBaby', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Polo G', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'NBA YoungBoy', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Moneybagg Yo', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Lil Uzi Vert', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Pop Smoke', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'A$AP Rocky', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Tyler, the Creator', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Meek Mill', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Rick Ross', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Kevin Gates', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Jack Harlow', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Fivio Foreign', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Latto', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Ice Spice', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'GloRilla', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Sexyy Red', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Doechii', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Playboi Carti', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Kodkodak Black', primaryGenre: 'R&B/Hip-Hop' },
  { name: '21 Savage', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Offset', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Quavo', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Don Toliver', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Central Cee', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Metro Boomin', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'SZA', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'H.E.R.', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Jhené Aiko', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Summer Walker', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Ari Lennox', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Giveon', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Lucky Daye', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Daniel Caesar', primaryGenre: 'R&B/Hip-Hop' },
  { name: 'Frank Ocean', primaryGenre: 'R&B/Hip-Hop' },

  // Pop (40)
  { name: 'Taylor Swift', primaryGenre: 'Pop' },
  { name: 'Billie Eilish', primaryGenre: 'Pop' },
  { name: 'Dua Lipa', primaryGenre: 'Pop' },
  { name: 'The Weeknd', primaryGenre: 'Pop' },
  { name: 'Ariana Grande', primaryGenre: 'Pop' },
  { name: 'Harry Styles', primaryGenre: 'Pop' },
  { name: 'Olivia Rodrigo', primaryGenre: 'Pop' },
  { name: 'Post Malone', primaryGenre: 'Pop' },
  { name: 'Ed Sheeran', primaryGenre: 'Pop' },
  { name: 'Justin Bieber', primaryGenre: 'Pop' },
  { name: 'Doja Cat', primaryGenre: 'Pop' },
  { name: 'Lizzo', primaryGenre: 'Pop' },
  { name: 'Sabrina Carpenter', primaryGenre: 'Pop' },
  { name: 'Charli XCX', primaryGenre: 'Pop' },
  { name: 'Gracie Abrams', primaryGenre: 'Pop' },
  { name: 'Benson Boone', primaryGenre: 'Pop' },
  { name: 'Teddy Swims', primaryGenre: 'Pop' },
  { name: 'Zach Bryan', primaryGenre: 'Pop' },
  { name: 'Noah Kahan', primaryGenre: 'Pop' },
  { name: 'Tate McRae', primaryGenre: 'Pop' },
  { name: 'Sia', primaryGenre: 'Pop' },
  { name: 'Camila Cabello', primaryGenre: 'Pop' },
  { name: 'Selena Gomez', primaryGenre: 'Pop' },
  { name: 'Lady Gaga', primaryGenre: 'Pop' },
  { name: 'Katy Perry', primaryGenre: 'Pop' },
  { name: 'Adele', primaryGenre: 'Pop' },
  { name: 'Rihanna', primaryGenre: 'Pop' },
  { name: 'Bruno Mars', primaryGenre: 'Pop' },
  { name: 'Charlie Puth', primaryGenre: 'Pop' },
  { name: 'Halsey', primaryGenre: 'Pop' },
  { name: 'Meghan Trainor', primaryGenre: 'Pop' },
  { name: 'Lewis Capaldi', primaryGenre: 'Pop' },
  { name: 'Kim Petras', primaryGenre: 'Pop' },
  { name: 'Sam Smith', primaryGenre: 'Pop' },
  { name: 'Conan Gray', primaryGenre: 'Pop' },
  { name: 'Troye Sivan', primaryGenre: 'Pop' },
  { name: 'Lana Del Rey', primaryGenre: 'Pop' },
  { name: 'Miley Cyrus', primaryGenre: 'Pop' },
  { name: 'Ava Max', primaryGenre: 'Pop' },
  { name: 'Bebe Rexha', primaryGenre: 'Pop' },

  // Rock & Alternative (25)
  { name: 'Imagine Dragons', primaryGenre: 'Rock & Alternative' },
  { name: 'Twenty One Pilots', primaryGenre: 'Rock & Alternative' },
  { name: 'Foo Fighters', primaryGenre: 'Rock & Alternative' },
  { name: 'Coldplay', primaryGenre: 'Rock & Alternative' },
  { name: 'Linkin Park', primaryGenre: 'Rock & Alternative' },
  { name: 'Green Day', primaryGenre: 'Rock & Alternative' },
  { name: 'Fall Out Boy', primaryGenre: 'Rock & Alternative' },
  { name: 'Panic! at the Disco', primaryGenre: 'Rock & Alternative' },
  { name: 'My Chemical Romance', primaryGenre: 'Rock & Alternative' },
  { name: 'Arctic Monkeys', primaryGenre: 'Rock & Alternative' },
  { name: 'Paramore', primaryGenre: 'Rock & Alternative' },
  { name: 'Muse', primaryGenre: 'Rock & Alternative' },
  { name: 'Kings of Leon', primaryGenre: 'Rock & Alternative' },
  { name: 'The 1975', primaryGenre: 'Rock & Alternative' },
  { name: 'Hozier', primaryGenre: 'Rock & Alternative' },
  { name: 'Weezer', primaryGenre: 'Rock & Alternative' },
  { name: 'Highly Suspect', primaryGenre: 'Rock & Alternative' },
  { name: 'Maneskin', primaryGenre: 'Rock & Alternative' },
  { name: 'Machine Gun Kelly', primaryGenre: 'Rock & Alternative' },
  { name: 'Badflower', primaryGenre: 'Rock & Alternative' },
  { name: 'Nothing But Thieves', primaryGenre: 'Rock & Alternative' },
  { name: 'Metallica', primaryGenre: 'Rock & Alternative' },
  { name: 'Red Hot Chili Peppers', primaryGenre: 'Rock & Alternative' },
  { name: 'Pearl Jam', primaryGenre: 'Rock & Alternative' },
  { name: 'Jack White', primaryGenre: 'Rock & Alternative' },

  // Country (20)
  { name: 'Morgan Wallen', primaryGenre: 'Country' },
  { name: 'Luke Combs', primaryGenre: 'Country' },
  { name: 'Chris Stapleton', primaryGenre: 'Country' },
  { name: 'Kacey Musgraves', primaryGenre: 'Country' },
  { name: 'Cody Johnson', primaryGenre: 'Country' },
  { name: 'Jelly Roll', primaryGenre: 'Country' },
  { name: 'Lainey Wilson', primaryGenre: 'Country' },
  { name: 'Tyler Hubbard', primaryGenre: 'Country' },
  { name: 'Bailey Zimmerman', primaryGenre: 'Country' },
  { name: 'Carly Pearce', primaryGenre: 'Country' },
  { name: 'Thomas Rhett', primaryGenre: 'Country' },
  { name: 'Cole Swindell', primaryGenre: 'Country' },
  { name: 'Dierks Bentley', primaryGenre: 'Country' },
  { name: 'Blake Shelton', primaryGenre: 'Country' },
  { name: 'Carrie Underwood', primaryGenre: 'Country' },
  { name: 'Megan Moroney', primaryGenre: 'Country' },
  { name: 'Zach Top', primaryGenre: 'Country' },
  { name: 'Warren Zeiders', primaryGenre: 'Country' },
  { name: 'Dustin Lynch', primaryGenre: 'Country' },
  { name: 'Kane Brown', primaryGenre: 'Country' },

  // Latin (20) - eligible for Other slot
  { name: 'Bad Bunny', primaryGenre: 'Latin' },
  { name: 'J Balvin', primaryGenre: 'Latin' },
  { name: 'Karol G', primaryGenre: 'Latin' },
  { name: 'Ozuna', primaryGenre: 'Latin' },
  { name: 'Rauw Alejandro', primaryGenre: 'Latin' },
  { name: 'Maluma', primaryGenre: 'Latin' },
  { name: 'Anuel AA', primaryGenre: 'Latin' },
  { name: 'Daddy Yankee', primaryGenre: 'Latin' },
  { name: 'Becky G', primaryGenre: 'Latin' },
  { name: 'Nicky Jam', primaryGenre: 'Latin' },
  { name: 'Farruko', primaryGenre: 'Latin' },
  { name: 'Jhay Cortez', primaryGenre: 'Latin' },
  { name: 'Myke Towers', primaryGenre: 'Latin' },
  { name: 'Sech', primaryGenre: 'Latin' },
  { name: 'Lunay', primaryGenre: 'Latin' },
  { name: 'Zion & Lennox', primaryGenre: 'Latin' },
  { name: 'Peso Pluma', primaryGenre: 'Latin' },
  { name: 'Fuerza Regida', primaryGenre: 'Latin' },
  { name: 'Eslabon Armado', primaryGenre: 'Latin' },
  { name: 'Grupo Frontera', primaryGenre: 'Latin' },

  // Dance (15)
  { name: 'David Guetta', primaryGenre: 'Dance' },
  { name: 'Calvin Harris', primaryGenre: 'Dance' },
  { name: 'Marshmello', primaryGenre: 'Dance' },
  { name: 'The Chainsmokers', primaryGenre: 'Dance' },
  { name: 'Diplo', primaryGenre: 'Dance' },
  { name: 'Kygo', primaryGenre: 'Dance' },
  { name: 'Zedd', primaryGenre: 'Dance' },
  { name: 'Skrillex', primaryGenre: 'Dance' },
  { name: 'Martin Garrix', primaryGenre: 'Dance' },
  { name: 'Tiësto', primaryGenre: 'Dance' },
  { name: 'Alesso', primaryGenre: 'Dance' },
  { name: 'ILLENIUM', primaryGenre: 'Dance' },
  { name: 'Alan Walker', primaryGenre: 'Dance' },
  { name: 'Disclosure', primaryGenre: 'Dance' },
  { name: 'Flume', primaryGenre: 'Dance' },

  // K-Pop (5) - eligible for Other slot
  { name: 'BTS', primaryGenre: 'K-Pop' },
  { name: 'BLACKPINK', primaryGenre: 'K-Pop' },
  { name: 'Stray Kids', primaryGenre: 'K-Pop' },
  { name: 'NewJeans', primaryGenre: 'K-Pop' },
  { name: 'TWICE', primaryGenre: 'K-Pop' },

  // Afrobeats (6) - eligible for Other slot
  { name: 'Wizkid', primaryGenre: 'Afrobeats' },
  { name: 'Burna Boy', primaryGenre: 'Afrobeats' },
  { name: 'Tems', primaryGenre: 'Afrobeats' },
  { name: 'Rema', primaryGenre: 'Afrobeats' },
  { name: 'Ayra Starr', primaryGenre: 'Afrobeats' },
  { name: 'Asake', primaryGenre: 'Afrobeats' },

  // Other (2) - eligible for Other slot
  { name: 'Tee Grizzley', primaryGenre: 'Other' },
  { name: 'EST Gee', primaryGenre: 'Other' },
];
